[2023-10-26T04:13:52.154+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:871: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti: TaskInstance | None = qry.with_for_update().one_or_none()

[2023-10-26T04:13:52.207+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: crawl_task.write_data_file manual__2023-10-26T04:13:45.725913+00:00 [queued]>
[2023-10-26T04:13:52.234+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: crawl_task.write_data_file manual__2023-10-26T04:13:45.725913+00:00 [queued]>
[2023-10-26T04:13:52.235+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-10-26T04:13:52.236+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-10-26T04:13:52.237+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-10-26T04:13:52.273+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): write_data_file> on 2023-10-26 04:13:45.725913+00:00
[2023-10-26T04:13:52.282+0000] {standard_task_runner.py:54} INFO - Started process 682 to run task
[2023-10-26T04:13:52.286+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'crawl_task', 'write_data_file', 'manual__2023-10-26T04:13:45.725913+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/crawl_task.py', '--cfg-path', '/tmp/tmpcqg_vfmz']
[2023-10-26T04:13:52.287+0000] {standard_task_runner.py:83} INFO - Job 5: Subtask write_data_file
[2023-10-26T04:13:52.293+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/crawl_task.py
[2023-10-26T04:13:52.811+0000] {task_command.py:384} INFO - Running <TaskInstance: crawl_task.write_data_file manual__2023-10-26T04:13:45.725913+00:00 [running]> on host ba88366ceb7b
[2023-10-26T04:13:52.814+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:873: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti = qry.one_or_none()

[2023-10-26T04:13:52.967+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=crawl_task
AIRFLOW_CTX_TASK_ID=write_data_file
AIRFLOW_CTX_EXECUTION_DATE=2023-10-26T04:13:45.725913+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-26T04:13:45.725913+00:00
[2023-10-26T04:13:57.418+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:873: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti = qry.one_or_none()

[2023-10-26T04:14:42.572+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-10-26T04:14:42.593+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=crawl_task, task_id=write_data_file, execution_date=20231026T041345, start_date=20231026T041352, end_date=20231026T041442
[2023-10-26T04:14:42.631+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-10-26T04:14:42.677+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
